zoom_in_icon:
  default: search-plus
  type: "string"
  description: "You can change the (zoom in) button icon here."
zoom_out_icon:
  default: search-minus
  type: "string"
  description: "You can change the (zoom out) button icon here."
close_icon:
  default: times
  type: "string"
  description: "You can change the (close) button icon here."  
svg_icons: 
  default: "search-plus|search-minus"
  type: "list"
  list_type: "compact"
  description: "List of FontAwesome 5 icons used in this theme component"
hide_download_button:
  default: false
  type: "bool"
  description: "Hide download button."
buttons_position_mobile:
  default: close and zoom bottom left, download top left
  type: enum
  choices:
    - close and zoom top right, download top left
    - close and zoom top right, download bottom left
  description: "Close, Zoom and Download buttons position on mobile."
